"use client";
import { FormEvent, useState } from "react";
import { Loader2, Plus } from "lucide-react";
import { useRouter } from "next/navigation";
import { useToast } from "@/components/toast-provider";

export function NotesManager({ subjects, notes }: { subjects: { id: string; titulo: string }[]; notes: { id: string; titulo: string; conteudo: string; atualizadoEm: string; materia: { titulo: string } | null }[] }) {
 const [open,setOpen]=useState(false),[pending,setPending]=useState(false); const {notify}=useToast(); const router=useRouter();
 async function submit(event: FormEvent<HTMLFormElement>){ event.preventDefault(); setPending(true); const form=new FormData(event.currentTarget); try { const response=await fetch("/api/notes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({titulo:form.get("titulo"),conteudo:form.get("conteudo"),materiaId:form.get("materiaId")||null})}); const result=await response.json(); if(!response.ok) throw new Error(result.message); setOpen(false); notify("success","Anotação criada."); router.refresh(); } catch(error){notify("error",error instanceof Error?error.message:"Não foi possível criar a anotação.");} finally{setPending(false);} }
 return <div>{!open?<button onClick={()=>setOpen(true)} className="btn-primary"><Plus className="h-4 w-4"/> Nova anotação</button>:<form onSubmit={submit} className="mt-6 grid gap-4 rounded-3xl border border-emerald-100 bg-emerald-50/50 p-5"><label>Título<input name="titulo" required minLength={2} maxLength={150} className="mt-1.5" placeholder="Ex.: Regras de crase"/></label><label>Disciplina<select name="materiaId" className="mt-1.5"><option value="">Sem disciplina</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.titulo}</option>)}</select></label><label>Anotação<textarea name="conteudo" required maxLength={20000} rows={6} className="mt-1.5" placeholder="Registre ideias, dúvidas e pontos importantes..."/></label><div className="flex gap-3"><button disabled={pending} className="btn-primary">{pending&&<Loader2 className="h-4 w-4 animate-spin"/>}Salvar</button><button type="button" onClick={()=>setOpen(false)} className="btn-secondary">Cancelar</button></div></form>}<div className="mt-6 grid gap-4 md:grid-cols-2">{notes.map(note=><article key={note.id} className="rounded-2xl border border-stone-200 bg-white p-5"><h2 className="font-semibold text-stone-950">{note.titulo}</h2>{note.materia&&<p className="mt-1 text-xs font-semibold text-emerald-800">{note.materia.titulo}</p>}<p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-stone-600">{note.conteudo}</p><p className="mt-4 text-xs text-stone-400">Atualizada em {new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(note.atualizadoEm))}</p></article>)}</div>{!notes.length&&!open&&<p className="mt-6 rounded-2xl border border-dashed border-stone-300 p-8 text-center text-sm text-stone-600">Crie sua primeira anotação para guardar pontos importantes.</p>}</div>;
}
