"use client";
import { useState } from "react";
import { ChevronLeft, ChevronRight, Expand, Loader2, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { useToast } from "@/components/toast-provider";

export function PdfReader({ id, title, url, pages, currentPage, onProgressSaved }: { id: string; title: string; url: string; pages: number | null; currentPage: number | null; onProgressSaved?: (page: number) => void }) {
  const [open, setOpen] = useState(false); const [page, setPage] = useState(currentPage ?? 1); const [savedPage, setSavedPage] = useState(currentPage ?? 1); const [saving, setSaving] = useState(false); const { notify } = useToast(); const router = useRouter();
  async function save(next = page) { setSaving(true); try { const r = await fetch(`/api/materials/${id}/progress`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ paginaAtual: next }) }); const data = await r.json(); if (!r.ok) throw new Error(data.message); setSavedPage(next); onProgressSaved?.(next); notify("success", `Página ${next} salva.`); router.refresh(); } catch (error) { notify("error", error instanceof Error ? error.message : "Não foi possível salvar a página."); } finally { setSaving(false); } }
  function move(delta: number) { const next = Math.max(1, Math.min(pages ?? Number.MAX_SAFE_INTEGER, page + delta)); setPage(next); save(next); }
  return <><button type="button" onClick={() => setOpen(true)} className="btn-secondary text-sm"><Expand className="h-4 w-4" /> Ler no app</button>{open && <div className="fixed inset-0 z-50 bg-stone-950/50 p-3 sm:p-6"><section role="dialog" aria-modal="true" aria-label={`Leitor: ${title}`} className="mx-auto flex h-full max-w-6xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl"><header className="flex items-center justify-between gap-3 border-b border-stone-200 px-4 py-3"><div className="min-w-0"><p className="truncate font-semibold text-stone-950">{title}</p><p className="text-xs text-stone-500">Página {page}{pages ? ` de ${pages}` : ""}</p></div><button onClick={() => setOpen(false)} className="rounded-lg p-2 text-stone-500 hover:bg-stone-100" aria-label="Fechar leitor"><X className="h-5 w-5" /></button></header><div className="flex flex-1 items-center justify-center bg-stone-100"><iframe key={page} src={`${url}#page=${page}`} title={title} className="h-full w-full border-0" /></div><footer className="flex items-center justify-between border-t border-stone-200 px-4 py-3"><button onClick={() => move(-1)} disabled={saving || page <= 1} className="btn-secondary text-sm"><ChevronLeft className="h-4 w-4" /> Anterior</button><button onClick={() => save()} disabled={saving} className="text-sm font-semibold text-emerald-800">{saving ? <Loader2 className="inline h-4 w-4 animate-spin" /> : savedPage === page ? `Página ${page} salva` : "Salvar página"}</button><button onClick={() => move(1)} disabled={saving || Boolean(pages && page >= pages)} className="btn-secondary text-sm">Próxima <ChevronRight className="h-4 w-4" /></button></footer></section></div>}</>;
}
