import { CalendarCheck2, Check, Clock3, RotateCcw } from "lucide-react";

const reviews = [
  { title: "Funções orgânicas", material: "Funções orgânicas — slides", time: "Hoje, 19:00", status: "Agora" },
  { title: "Era Vargas", material: "Brasil República.pdf", time: "Amanhã, 09:00", status: "A seguir" },
  { title: "Princípios fundamentais", material: "Direito constitucional.pdf", time: "Sexta, 18:30", status: "Planejada" }
];

export default function ReviewsPage() {
  return <div className="mx-auto max-w-6xl"><div><p className="text-sm font-semibold text-emerald-800">Memória em movimento</p><h1 className="mt-1 text-3xl font-semibold tracking-[-0.04em] text-stone-950 sm:text-4xl">Revisões</h1><p className="mt-2 text-stone-600">Volte aos pontos certos no momento certo.</p></div><section className="mt-8 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-emerald-900 p-5 text-white"><RotateCcw className="h-5 w-5 text-emerald-200" /><p className="mt-8 text-3xl font-semibold">1</p><p className="mt-1 text-sm text-emerald-100">revisão para hoje</p></div><div className="rounded-2xl border border-stone-200 bg-white p-5"><CalendarCheck2 className="h-5 w-5 text-emerald-800" /><p className="mt-8 text-3xl font-semibold text-stone-950">3</p><p className="mt-1 text-sm text-stone-600">nos próximos 7 dias</p></div><div className="rounded-2xl border border-stone-200 bg-[#fff8e7] p-5"><Clock3 className="h-5 w-5 text-amber-700" /><p className="mt-8 text-3xl font-semibold text-stone-950">12 min</p><p className="mt-1 text-sm text-stone-600">tempo estimado hoje</p></div></section><section className="mt-10"><p className="text-sm font-bold uppercase tracking-[0.14em] text-stone-400">Sua sequência</p><div className="mt-4 overflow-hidden rounded-2xl border border-stone-200 bg-white">{reviews.map((review, index) => <article key={review.title} className="flex items-center gap-4 border-b border-stone-100 p-5 last:border-0"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-emerald-50 text-emerald-800"><span className="text-sm font-bold">0{index + 1}</span></span><div className="min-w-0 flex-1"><h2 className="font-semibold text-stone-950">{review.title}</h2><p className="mt-0.5 truncate text-sm text-stone-500">{review.material}</p></div><div className="text-right"><span className="badge">{review.status}</span><p className="mt-2 text-xs font-medium text-stone-500">{review.time}</p></div>{index === 0 && <button className="btn-primary hidden sm:inline-flex"><Check className="h-4 w-4" /> Revisar</button>}</article>)}</div></section></div>;
}
